/** Data model for the catalog (generated by `scripts/generate-data.mjs`). */

export type ProfessionalCategory =
  | 'Serviços Domésticos'
  | 'Construção e Reforma'
  | 'Tecnologia'
  | 'Saúde e Bem-estar'
  | 'Beleza e Estética'
  | 'Educação'
  | 'Eventos'
  | 'Automotivo'

export type SortOption = 'price_asc' | 'price_desc' | 'rating' | 'distance'

export interface Professional {
  id: string
  name: string
  profession: string
  category: ProfessionalCategory
  avatarUrl: string | null
  price: number
  rating: number
  distanceKm: number
  city: string
  description: string
  services: string[]
  availability: string[]
}

export interface ProfessionalsResponse {
  items: Professional[]
  total: number
  page: number
  limit: number
  totalPages: number
}

export interface ProfessionalsQuery {
  search?: string
  category?: ProfessionalCategory
  sort?: SortOption
  page?: number
  limit?: number
}
